default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rspgame_development
test:
  <<: *default
  database: rspgame_test
production:
  <<: *default
  database: rspgame_production
  username: rspgame
  password: <%= ENV['RSPGAME_DATABASE_PASSWORD'] %>
